name: pangpang_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    # 언어 설정
  flutter_localizations:
    sdk: flutter

  
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.3  
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.1.3
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  lottie: ^3.3.1
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_secure_storage: ^9.2.4 #ios에서 키체인으로 저장됨, 한 번 더 보완 레이어가 있는 저장 시스템
  flutter_naver_map: ^1.4.1+1
  skeletons: ^0.0.3
  video_player: ^2.10.0
  flutter_quill: ^11.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - .env
  
  
  fonts:
    - family: omyu-pretty
      fonts:
        - asset: assets/fonts/omyu-pretty.ttf
